ARG BASE_IMAGE=ghcr.io/verrazzano/verrazzano-base:v1.0.0-20230811160107-63554aa
ARG FINAL_IMAGE=ghcr.io/verrazzano/ol8-static:v0.0.1-20231102152128-e7afc807
FROM $BASE_IMAGE AS builder

RUN microdnf install -y go-toolset make git && \
    microdnf --enablerepo ol8_codeready_builder install glibc-static && \
    microdnf clean all && \
    rm -rf /var/cache/yum/*

WORKDIR /usr/local/src/dex

ENV CGO_ENABLED=1

COPY go.mod go.sum ./
COPY api/v2/go.mod api/v2/go.sum ./api/v2/
RUN go mod download

COPY . .
RUN make release-binary

FROM $BASE_IMAGE AS stager

RUN mkdir -p /var/dex
RUN mkdir -p /etc/dex

COPY config.dev.yaml /etc/dex/

# Create a directory for sqlite3 path used in config.dev.yaml
# This is used only when the image is run using docker run
RUN mkdir -p /var/sqlite

FROM $FINAL_IMAGE

COPY --from=stager --chown=1001:1001 /var/dex /var/dex
COPY --from=stager --chown=1001:1001 /etc/dex /etc/dex
COPY --from=stager --chown=1001:1001 /var/sqlite /var/sqlite

# Copy module files for CVE scanning / dependency analysis.
COPY --from=builder /usr/local/src/dex/go.mod /usr/local/src/dex/go.sum /usr/local/src/dex/
COPY --from=builder /usr/local/src/dex/api/v2/go.mod /usr/local/src/dex/api/v2/go.sum /usr/local/src/dex/api/v2/

COPY --from=builder /go/bin/dex /usr/local/bin/dex
COPY --from=builder /usr/local/src/dex/web /srv/dex/web

USER 1001:1001

CMD ["/usr/local/bin/dex", "serve", "/etc/dex/config.dev.yaml"]
